import 'dotenv/config';

const {
  AWS_COMPREHEND_ROLE_ARN, AWS_JOB_OUTPUT_BUCKET, TOPIC_JOB_ID, HOST_URL, MOCK_METHOD,
  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION
} = process.env;

const config = { AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION };

export {
  config,
  AWS_COMPREHEND_ROLE_ARN,
  AWS_JOB_OUTPUT_BUCKET,
  TOPIC_JOB_ID,
  HOST_URL,
  MOCK_METHOD
};
